name = "cfw-bun-hono-drizzle"
compatibility_date = "2023-12-01"
compatibility_flags = [ "nodejs_compat" ]


[vars]
KV_STORE="IDB_KEYVAL"
MY_VAR = "my-variable"
JWT_SECRET = "default-secret-for-testing"
JWT_FINGERPRINT_COOKIE_NAME="__Secure-Fgp"
JWT_FINGERPRINT_REFRESH_COOKIE_NAME="__Secure-Fgp-Refresh"

ALLOWED_ORIGINS = "https://localhost:5173"

# Token expiration in minutes
REFRESH_TOKEN_EXPIRATION = 1440
TOKEN_EXPIRATION = 5


[[kv_namespaces]]
binding = "IDB_KEYVAL"
id = "5bd608872f1942f69f463173086e3842"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "f2fpos"
database_id = "9b9c3f4c-e50f-4194-9a53-4923c8d13eb7"

# [ai]
# binding = "AI"
